name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.6  # only CLI version, nothing else

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./Deploy-EC2
        run: terraform init

      - name: Terraform Plan
        working-directory: ./Deploy-EC2
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./Deploy-EC2
        run: terraform apply -auto-approve tfplan
